.\" mqtt-sys.1:
.\"
.\" This file is a part of the mqtt-sys package by Jan-Piet Mens
.\"
.TH mqtt-sys 1 "May 2015"
.SH NAME
mqtt-sys \- MQTT "$SYS/#"-subscriber for collectd exec
.SH SYNOPSYS
.B mqtt-sys [-h
.I host
.B ]
.B [-p
.I port
.B ] [-C
.I CA-cert
.B ] [-u
.I username
.B ] [-P
.I password
.B ] [-K
.I psk-key
.B ] [-I
.I psk-identity
.B ] [-s] [-N
.I nodename
.B ] [-f
.I metrics
.B ] [-t
.I topic...
.B ]

.SH DESCRIPTION

.I mqtt-sys
is an executable program which is used with
.IR collectd (1).
It subscribes to the MQTT $SYS/# topic and/or to any number of topics
you specify, and prints values to
.I stdout
for
.I collectd
to process in an
.I exec
plugin block.
.PP
.nf
PUTVAL tiggr/mqtt-sys/gauge-clients.inactive 1430914033:0.00
\...
.fi

.PP
.I collectd
launches
.I mqtt-sys
which connects to the configured MQTT broker, subscribes and waits for publishes to subscribed topics in an
endless loop. If an error occurs or the program exits for whichever reason,
.I collectd
will restart it, and
.I collectd
logs the reason it its log file.

.SS "MQTT subscriptions"

By default,
.I mqtt-sys
subscribes to the $SYS/# topic tree of the specified MQTT broker, but any number of topic subscriptions can be set up using the
.BR -t option.
Whether or not the payload of a received message is actually passed to
.I collectd
is defined by a
.I metrics map
which maps an MQTT topic name to a metric name with a particular type and its numeric value.
It is therefore quite possible that
.I mqtt-sys
is subscribed to a topic but doesn't pass that to
.IR collectd .
(This is known as a configuration error.)

.SS "Metrics map"

The MQTT
.I topic
to
.I collectd metrics
mapping is configured through a
.I metrics
file you provide. Lines which start with # and empty lines are ignored.
All other lines must have three white-space separated tokens.
The
.I metric name
which is what is passed to
.IR collectd ,
the
.I type
of the metric (from
.IR types.db ),
and the MQTT
.IR "topic name" .
.PP
.nf
temp.living        gauge   arduino/temp/celsius
bROKER.UPTIme      uptime  $SYS/broker/uptime
*                  gauge   $SYS/broker/heap/maximum
msgs.count         gauge   $SYS/broker/retained messages/count`
.fi
.PP

As a special case, if the
.I metric
name is an asterisk (
.BR * )
the original topic name is used as the name of the metric.

.SS InfluxDB

As an example, we show how to configure
.I InfluxDB
to accept values from
.I collectd
via the latter's
.I network
plugin.  Configure
.I InfluxDB
to launch the native collectd input:

.nf
[input_plugins]

  [input_plugins.collectd]
  enabled = true
  # address = "0.0.0.0" # defaults to bind-address.
  port = 25826
  database = "collectd"
  # https://github.com/collectd/collectd/blob/master/src/types.db
  typesdb = "/usr/share/collectd/types.db"
.fi

.SS collectd

Configure
.I collectd
to send its metrics to
.I InfluxDB
via the
.I network
plugin which talks to
.IR InfluxDB .
(Compare the port numbers here and above in
.IR InfluxDB .)

.nf
LoadPlugin network

<Plugin "network">
  # influxdb
    Server "127.0.0.1" "25826"
</Plugin>
.fi

Configure
.I collectd
to load our executable
.I mqtt-sys
via its
.I exec
mechanism. Specify
.I mqtt-sys
options as individual strings in the "Exec" invocation.

.nf
LoadPlugin exec

<Plugin exec>
   Exec "mosquitto:mosquitto" "/usr/bin/mqtt-sys" "-u" "jjolie" "-P" "secret"
</Plugin>
.fi

.SS Testing

Launch
.I mqtt-sys
on the command line; you should see PUTVAL statements being printed. If that works
configure
.I collectd
as described above.

To see if whether your values are being passed to
.IR InfluxDB :

.nf
select * from "hippo/mqtt-sys/connections-connections.1m"
select * from "hippo/mqtt-sys/counter-msgs.received"
.fi

.SH OPTIONS

.IP "\fB\-C\fR \fIca-file\fR"
specifies the PEM-encoded CA certificate file to use for TLS.

.IP "\fB\-h \fIhost\fR"
is the hostname or address of the MQTT broker. Unless overriden by
.B -N
this also sets the collectd
.IR nodename .

.IP "\fB\-p \fIport\fR"
gives the TCP port number for the MQTT broker; defaults to 1883.

.IP "\fB\-s\fR"
use insecure TLS.

.IP "\fB\-f \fImetrics\fR"
is the path to the metrics file which defaults to "/usr/local/etc/mqtt-sys.metrics". If
this file cannot be read, the program exits with a diagnostic
message.

.IP "\fB\-I \fIpsk-identity\fR"
sets the identity for PSK.

.IP "\fB\-t \fItopic\fR"
may be specified multiple times and causes
.I mqtt-sys
to subscribe to that topic. Defaults to "$SYS/#" if not specified.

.IP "\fB\-u  \fIusername\fR"
for the MQTT connection. This overrides
.B $MQTTSYSUSER
if set.

.IP "\fB\-P  \fIpassword\fR"
for the MQTT connection. This overrides
.B $MQTTSYSPASS
if set.

.IP "\fB\-K  \fIpsk-key\fR"
for the MQTT connection.


.IP "\fB\-N  \fInodename\fR"
Overrides the
.IR collectd
node name, which without this option, defaults to the short local hostname or the value of the
.B -h
option

.SH ENVIRONMENT

.I mqtt-sys
uses the values
.B MQTTSYSUSER and
.B MQTTSYSPASS
to predefine username and password for the
.B -u
and
.B -p
options respectively.

.SH AUTHOR

Jan-Piet Mens

.SH BUGS

Options (such as
.B -u
and
.BR -p )
specified on the command line are visible in the system's process list and thus by other users.

.SH "SEE ALSO"

.IR collectd (1),
.IR mosquitto (8),
.IR uthash (3).

